<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Log4j</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.trace.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TRACE log</string>
			<key>match</key>
			<string>^(\[)(TRACE)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.debug.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>DEBUG log</string>
			<key>match</key>
			<string>^(\[)(DEBUG)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.info.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>INFO log</string>
			<key>match</key>
			<string>^(\[)(INFO)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>WARN log</string>
			<key>match</key>
			<string>^(\[)(WARN)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ERROR log</string>
			<key>match</key>
			<string>^(\[)(ERROR)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>control.log4j</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.message.log4j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ERROR log</string>
			<key>match</key>
			<string>^(\[)(FATAL)(\]\[)(.+)(\]: )(.+)$</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.log4j</string>
	<key>uuid</key>
	<string>59d2eab0-506c-4c33-8e2f-a6a74820383a</string>
</dict>
</plist>
